version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt install -y php7.2-mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      
      - run: cp .env.testing .env

      - run: php artisan db:seed

      # run tests!
      - run: ./vendor/bin/phpunit
